apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-exporter
  name: kafka-exporter
  namespace: kafka
spec:
  ports:
    - port: 9308
  selector:
    app: kafka-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-exporter
  name: kafka-exporter
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      hostname: kafka-exporter
      containers:
        - image: danielqsj/kafka-exporter
          args:
            - '--zookeeper.server=$(ZOOKEEPER_SERVICE_PORT_2181_TCP_ADDR):2181'
            - '--kafka.server=kafka-service:9092'
          imagePullPolicy: IfNotPresent
          name: kafka-kafka-exporter
          ports:
            - containerPort: 9308
