apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
  - https://github.com/tektoncd/dashboard/releases/download/v0.39.0/release-full.yaml
  - tekton-dashboard-ingress.yaml
  #- tekton-dashboard-vs.yaml
