apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 60m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: istiod
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 60m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: "1.16.1"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 60m
